<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Day of the Week Calculator</title>
<script>
function calculateDay(inputDate) {
    var dateObject = new Date(inputDate);
    var dayIndex = dateObject.getDay();
    var dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
    var output = "The day is: " + dayNames[dayIndex];
    document.getElementById("output").innerHTML = output;
}
</script>
</head>
<body>
    <h2>Day of the Week Calculator</h2>
    <label for="inputDate">Enter a date:</label>
    <input type="date" id="inputDate">
    <button onclick="calculateDay(document.getElementById('inputDate').value)">Calculate</button>
    <div id="output"></div>

    <?php
    // PHP code to generate the current date
    $currentDate = date('Y-m-d');
    ?>

    <script>
    // Pass the current date generated by PHP to the JavaScript function
    calculateDay('<?php echo $currentDate; ?>');
    </script>
</body>
</html>
